language: java
dist: trusty
jdk:
- oraclejdk8
before_script:
- "./gradlew test"
script:
- "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: r+Vuc5NC0qbIbN9tdvqebkytzmeCBXFPT63d7S/J36ZSj/jQcYYaxAD9dCtfAsBpVp1spfBchFEIJN44VJ7h2IzC6wHH6IKsN/bCk7JCkP8jFvdVo8O7phgVudox4uC0w8P5b5xyyjrdj6FCh/RHEe4myU01TTb86YCc+Csqv53U7J4MbFGhdA2Ojzq7qkH6t8hx+Lj0rnjQLH9yO8AgzVkAcB26PRW+NcXcsIsM60fw9rBK8p9QcvwTCgvdTAvC0E88fb96F45HxJ8Ho5RaBGey8rVGZHwLqCvb5RIYFC0KwIgZ6D8crs1NUvbxLnBmSJkfqfFBNbS7ekX99zmVMpc9h8n8AoWKtwrOe0atJTMUx+ZpBPdvHfdoYNB2Pi7pieb6No2jzaURLVq0RPwnzEReZtaUFOh19kBNC1YxUppCGuB1BJyrw26FlnrU1XqS7b0lImfVg1A6s9wC1NqxVFuDCDr5w7MUy1tJfFpspknexJgnUQFxlDiWpKlvrM5FOGCoB+BZeSl04chku0iWIc8YKlOsKnUDAtOQgX8MlYhAelxHyydLxuiDkyyl5+Bb1Wrtw5rJrmNSwbQYZig1u/lRDpSNoMLwd7X8LqW62WUG6+kXwe6QpDFNw3aL5E4U1QPUIG7p02uDvJQlv+uKRqgVOgmEXAdrFyIFKXaiUyQ=
  app: training-oocl
  on:
    repo: TWweihuang/heroku-spring-demo
