server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://ec2-18-235-4-83.compute-1.amazonaws.com:5432/d6c815538ed5a4
    driverClassName: org.postgresql.Driver
    maxActive: 5
    maxIdle: 2
    minIdle: 1
    initialSize: 2
    removeAbandoned: true
    username: aumtsfcmjrhjkg
    password: 3a2b73c6e1b543bfa8690a1643cba46f17f9c2251c3b82e6b5fb8963c261ad6d
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
